# Generated by Django 3.2 on 2022-03-12 10:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('movie_type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('CHILDREN', 'CHILDREN'), ('NEW_RELEASE', 'NEW_RELEASE')], max_length=255)),
                ('genre', models.CharField(choices=[('ACTION', 'ACTION'), ('DRAMA', 'DRAMA'), ('ROMANCE', 'ROMANCE'), ('COMEDY', 'COMEDY'), ('HORROR', 'HORROR')], max_length=255)),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('maximum_age', models.IntegerField(blank=True, null=True)),
                ('year_released', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 3, 12, 10, 6, 11, 528660, tzinfo=utc), max_length=255)),
                ('updated', models.DateTimeField(default=datetime.datetime(2022, 3, 12, 10, 6, 11, 528679, tzinfo=utc), max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('CHILDREN', 'CHILDREN'), ('NEW_RELEASE', 'NEW_RELEASE')], max_length=255)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
