# Generated by Django 3.2 on 2022-03-12 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 18, 31, 44103, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 18, 31, 44124, tzinfo=utc), max_length=255),
        ),
    ]
