# Generated by Django 3.2 on 2022-03-12 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220312_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 29, 36, 460011, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('CHILDREN', 'CHILDREN'), ('NEW RELEASE', 'NEW_RELEASE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 29, 36, 460029, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='movie_type',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('CHILDREN', 'CHILDREN'), ('NEW RELEASE', 'NEW_RELEASE')], max_length=255),
        ),
    ]
